# Generated by Django 4.2.23 on 2025-06-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publishedpost_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('X', 'X'), ('LI', 'LinkedIn'), ('TT', 'TikTok'), ('YT', 'YouTube')], max_length=2),
        ),
    ]
