# Generated by Django 4.2.23 on 2025-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_socialaccount_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
