# Generated by Django 4.2.23 on 2025-07-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_twitter_to_x'),
        ('core', '0004_content_is_draft'),
    ]

    operations = [
    ]
